# Spring
server:
    port: 6000
spring:
    cloud:
        gateway:
            routes:
                -   id: security
                    uri: http://localhost:6001
                    predicates:
                    -   Path=/security/**
                    filters:
                    -   StripPrefix=1
                -   id: invoice
                    uri: http://localhost:6002
                    predicates:
                    -   Path=/invoice/**
                    filters:
                    -   StripPrefix=1
                    -   JwtAuthenticationFilter
                -   id: pay
                    uri: http://localhost:6003
                    predicates:
                    -   Path=/pay/**
                    filters:
                    -   StripPrefix=1
                    -   JwtAuthenticationFilter
                -   id: transaction
                    uri: http://localhost:6004
                    predicates:
                    -   Path=/transaction/**
                    filters:
                    -   StripPrefix=1
                    -   JwtAuthenticationFilter
